name: 'Decrypt SOPS Secrets'
description: 'Run sops to decrypt secrets'

branding:
  icon: unlock
  color: red

inputs:
  ENVIRONMENT:
    required: true
    description: 'Which environment: dev, sit, stg, prod'
  CLIENT:
    required: true
    description: 'Which client: default, vrtp ...'
  PROJECT:
    required: true
    description: 'white-label, backend, infra'
#  AZURE_RESOURCE_GROUP:
#    required: true
#    description: 'az rg use'
#  AZURE_CLUSTER_NAME:
#    required: true
#    description: 'az cluster'
#  K8S_NAMESPACE:
#    required: true
#    description: 'k8s namespace'
  REPO_WORKING_DIR:
    required: true
    description: 'Folder with the Dockerfile'
  AZURE_CREDENTIALS:
    required: true
    description: 'Az credential'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
#    - name: Set up Go 1.18
#      uses: actions/setup-go@v1
#      with:
#        go-version: 1.18
    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
    - shell: bash
      id: init
      working-directory: ${{inputs.WORKING_DIR}}
      run: |
#        apt install sops
        ls
        sops -v
