name: 'Decrypt SOPS Secrets'
description: 'Run sops to decrypt secrets'

branding:
  icon: unlock
  color: red

inputs:
  ENVIRONMENT:
    required: true
    description: 'Which environment: dev, sit, stg, prod'
  CLIENT:
    required: true
    description: 'Which client: default, vrtp ...'
  PROJECT:
    required: true
    description: 'white-label, backend, infra'
  WORKING_DIR:
    required: true
    description: 'File with script'
  AZURE_CREDENTIALS:
    required: true
    description: 'Az credential'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1.2.0
    - uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}
    - shell: bash
      name: Decrypt files
      working-directory: ${{inputs.WORKING_DIR}}
      run: |
        ./decrypt.sh  ${{inputs.ENVIRONMENT}} ${{inputs.CLIENT}}
        ls -al
