name: 'Decrypt SOPS Secrets'
description: 'Run sops to decrypt secrets'

branding:
  icon: unlock
  color: red


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
    - shell: bash
      id: init
      working-directory: ${{inputs.WORKING_DIR}}
      run: |
        go get -u go.mozilla.org/sops/cmd/sops
        ls
        sops -v
